
== terms
Status: *Stable*

A network diagram based on the results of an Elasticsearch terms facet.

=== Parameters

sourceField:: The source field on which to computer the facet
size1:: Show this many terms for field 1
targetField:: The target field on which to computer the facet
size2:: Show this many terms for field 2
order:: How the terms are sorted: count, term, reverse_count or reverse_term, before they are filtered
exclude:: terms to exclude from the results
charge:: defines the charge for the forced layout network
counter_pos:: The location of the legend in respect to the diagram: above, below, or none.
arrangement:: Arrangement of the legend: horizontal or vertical
colorcode:: Indicates if the nodes should be coloured or black-white
nodeSize:: Indicates if the size of the nodes (radius) should be proportional to the incoming, outgoing ot total number of edges
directed:: defines if the paths in the network should be directed (true) or undirected (false)
tooltipSetting:: Indicates if tooltips should be shown if the user hovers over a segment or chord
sortingTooltip:: defines by which criteria the connections in the tooltip should be sorted
sortingOrderTooltip:: defines if the nodes should be ordered ascending (true) or descending (false)
tooltipOrientation:: defines if the nodes should be ordered ascending or descending
spyable:: Set spyable to false to disable the inspect button

==== Queries
queries object:: This object describes the queries to use on this panel.
queries.mode::: Of the queries available, which to use. Options: +all, pinned, unpinned, selected+
queries.ids::: In +selected+ mode, which query ids are selected.
